### ISSUE TITLE
Tidal breaks when application in maximized mode??

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#13]
Probably not related to tidal itself but just to document it, when using tidal with some extensions like [GTK Title Bar](https://extensions.gnome.org/extension/1732/gtk-title-bar/) tidal kind of breaks and starts behaving in a buggy way, sometimes the gnome shell even restarts it's session because it kind crashes.
As I said, probably not related to tidal itself but it is good to know that this kind of issue exists.

**Comment by rustysec** [comment]
i'll install it later tonight and see what i can figure out

**Comment by rustysec** [comment]
I installed [GTK Title Bar from git](https://github.com/velitasali/GTKTitleBar) and haven't noticed any issues so far (testing with vscodium). I don't have any electron apps in my daily workflow, are there any other steps you can think of to trigger a bug?

**Comment by REIS0** [comment]
For real I can't think of, I've stopped using it since yesterday because I'm using dynamic workflows now, maybe a bug of my computer itself since I have not tested it in other machines or vms

**Comment by rustysec** [comment]
Do you mean dynamic work spaces? Stopped using tidal or gtk title bar?

**Comment by REIS0** [comment]
sorry for the terrible comment, yes I've started using dynamic workspaces again so I disabled tidal

**Comment by rustysec** [comment]
No worries. I too, miss my dynamic workspaces. I added an issue to support it.

**Comment by REIS0** [comment]
I'm closing this one since I could not reproduce the bug again, really don't know what caused it maybe something in the gnome session.

**Comment by REIS0** [comment]
Looks like it wasn't an extension at all, got the same one even with the other extensions disabled, looks like when I try to make firefox in a maximized mode, like when a I double click it, it triggers the bug and the gnome shell restarts

here you can note that the firefox isn't in maximized mode since there's a little gap on the top left corner.
![image](https://user-images.githubusercontent.com/38042161/73316156-08af7e80-422a-11ea-8092-51815097dffc.png)

here is firefox without the gap and in maximized mode
![image](https://user-images.githubusercontent.com/38042161/73316277-5fb55380-422a-11ea-8d89-438ab70a1435.png)

So after trying some things this could be the trigger to this bug, of course you can use it without maximized mode and nothing occurs, but so far is something that we should know that can happen.

**Comment by rustysec** [comment]
Interesting... I'm running firefox right now and can't get it to break. I run my VirtualBox guests in maximized mode all the time as well. Are you on the latest master branch?

**Comment by REIS0** [comment]
Can you try something? I've been trying to reproduce this for quite sometime and looks like I've finally found (at least I expect)

Possibly steps that I've done that caused this:

- Opened an electron app, in my case is the whatsdesk from snapstore
- Move the app to my second monitor
- Open an app that is assigned to this monitor (the behaviour that if you open an app in a certain monitor, unless is electron made, it opens again in the last monitor it was in), in my case was telegram desktop from flatpak
- When telegram opens the tilling does not occur, they became both one above the other and gnome shell restarts

So far looks like is this, I'll continue to update this and try more things and yes I'm on the master branch.

Just to add that the dynamic workspace support is working great!

**Comment by rustysec** [comment]
I'll definitely play around with some electron apps and see if i can break it :)

**Comment by REIS0** [comment]
I could reproduce it with telegram downloaded directly from their website, apparently isn't directly related to flatpak

**Comment by rustysec** [comment]
Hrm... I've tried telegram and vscodium and can't trigger any kind of out of ordinary behavior... I'll keep investigating.

**Comment by REIS0** [comment]
Maybe something with snaps? I'll try to reproduce it with some snap apps that use electron
