### ISSUE TITLE
i3/Sway Tiling

### ISSUE THREAD

**Issue by rustysec** [rustysec/tidalwm#2]
Add tiling methods similar to [i3](https://github.com/i3/i3) or [sway](https://github.com/swaywm/sway).

**Comment by emargob** [comment]
So happy that I discovered this extension! Does exactly what I want, but it would be awesome to get i3 and binary tiling as well.

Any progress on that?

**Comment by rustysec** [comment]
I've decided not to pursue anything other than spiral tilling for now.
