### ISSUE TITLE
Tilling not really working when moving windows to other workspaces

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#20]
I've found something interesting, when I open two apps in one workspace, move one of them to the workspace below, and go back to the first workspace, the app that stayed in the first workspace don't resize.

example here with firefox
![image](https://user-images.githubusercontent.com/38042161/73325820-d90f6f00-4247-11ea-9a65-bc674b1fe28c.png)

Steps to reproduce:

- Open one app in a workspace, let's say workspace 1
- Open a second app in worskpace 1
- Move one of the apps to the workspace below, we can call it workspace 2, using keyboard shortcut (in my case is Super+Shift+Down)
- The app in the workspace 2 is resized as it should, however the app in workspace 1 stays as it was when it had a second app. (sometimes it happens that both don't resize)

Tested with different apps, using gtk or not, and could reproduce it without problems, looks like it's related to the new dynamic workspace support.

**Comment by rustysec** [comment]
This looks like a regression from dynamic workspace support, don't know how i didn't catch it before.

**Comment by rustysec** [comment]
just push a large change that should fix a few issues.

**Comment by rustysec** [comment]
Another sizable change, I'm still able to trigger a weird "remains as the original size" bug occasionally, but I have an idea what is going on. The stability of the current version should :+1:, however

**Comment by REIS0** [comment]
Sometimes this bug also happens to me, mostly when I move apps between my monitor, just moving closing them and opening again fix it

**Comment by rustysec** [comment]
i can usually grab the window, move it a little, then it resets correctly.

**Comment by REIS0** [comment]
One more thing to add, the command to rotate windows isn't working, tried using other keys but nothing, while the command to make the window float works

**Comment by REIS0** [comment]
I'm gonna close this one since there's already another issue related to "original size" bug #21

**Comment by rustysec** [comment]
> One more thing to add, the command to rotate windows isn't working, tried using other keys but nothing, while the command to make the window float works

Basically my dynamic workspace merge broke everything (:sob:), but I have a new branch where everything will be much better than before. Basically gutted all the internals with some lessons learned from all these bugs. The gnome docs on extensions aren't what I'd call excellent.

**Comment by REIS0** [comment]
I've been trying to read the beginners part of it and can't agree more
