### ISSUE TITLE
[suggestion] Hotkey to Increase / Reduce Split

### ISSUE THREAD

**Issue by kemmeo** [rustysec/tidalwm#24]
Just moved from the TilinGnome extensions and I'm really liking TidalWM, but I'm missing a way to increase & decrease the horizontal split using a hotkey. for example: "super + u" & "super + i". 
Each hotkey activation increasing or decreasing the split by 10%.

keep up the good work!

**Comment by rustysec** [comment]
I had a feeling this would come up at some point :smiley: It's not really part of my workflow so I was waiting until someone asked before I put any effort into it.

Thanks for the suggestion!

**Comment by REIS0** [comment]
this would be great

**Comment by rustysec** [comment]
I have a candidate implementation of this, but the custom splits don't remain if the window is closed. An example would be if you had a large main window and you adjust that to be 80% of the screen width. Then you open two more windows that are now on vertically split in that 20% left over space... closing a small window does not affect the 80% window. If that larger window is closed, however, the remaining windows are re-organized and go back to a normal 50%/50% split.

Is that intuitive? Or should the 80% remain when the windows are re-organized? Just looking for some outside opinions.

**Comment by rustysec** [comment]
first implementation of this is in #27
