### ISSUE TITLE
Keys to change between tilled windows

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#25]
This a suggestion to add key bindings to move between the tilled windows in the workspace, even though you can rotate the windows, the focus still in the same window, having to use alt+tab, which when working with many programs in different workspaces can be quite annoying.

As an example we can take the key bindings in i3 like $mod+j, $mod+k and so on.

EDIT: fix bad writing

**Comment by rustysec** [comment]
I map alt+tab to "switch to window directly" which works great. Directional navigation like sway/i3 is a great idea, however.
