### ISSUE TITLE
[Bug] Tilling sometimes gets this bizarre bug

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#30]
After the latest commit I'm getting this bug sometimes, this is happening in kind of a random mode so I really don't know how the hell to reproduce it.

As you can see the window is looking very small, but what also is strange is that the window itself don't recognize this and the interface becomes very buggy too
![image](https://user-images.githubusercontent.com/38042161/73782410-f5e8fc80-4789-11ea-90fb-d5adbae9600d.png)

EDIT: Okay I've just noticed a new commit about borders breaking, I'm gonna check if this solve this question.

**Comment by REIS0** [comment]
Closing since this was fixed 1 hour before opening this issue

**Comment by rustysec** [comment]
let me know if this is still a problem, that's odd behavior.
