### ISSUE TITLE
Minimized windows still take up space

### ISSUE THREAD

**Issue by kemmeo** [rustysec/tidalwm#32]
When I minimize a window the space on screen where it was is still reserved for it.
![Image of the issue](https://i.imgur.com/5s3nlxn.jpg)

**Comment by rustysec** [comment]
Hah! I will fix this in the morning. I never  minimize windows so never caught it 😂

**Comment by kemmeo** [comment]
Awesome, thanks so much! :)

**Comment by rustysec** [comment]
if pull master down and restart your gnome session, this should be working now. thanks for the report!
