### ISSUE TITLE
Select window shortcuts not working after last commits

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#34]
Basically the shortcuts don't work and after trying in another computer with a later version I've discovered that could be related to last commit, now I've rolled back to commit a9d34484c0cd52ba445996482adbd2e236aa074e which they're working without problems.

**Comment by rustysec** [comment]
That's odd, I'm using it right now... Wonder what could be wrong. I can possibly dig in tonight.

**Comment by rustysec** [comment]
What are your mappings?

**Comment by REIS0** [comment]
I've changed the <Super> to <Control><Alt> in them since it collides with the Pop_OS! shortcuts

**Comment by rustysec** [comment]
Are they working now?

**Comment by REIS0** [comment]
Yes, I'm gonna clone this one

**Comment by rustysec** [comment]
Awesome, glad to hear it.

**Comment by REIS0** [comment]
false positive, the problem is back, looks like I was dumb and didn't updated properly the extensions and it was on the old commit.

**Comment by rustysec** [comment]
What do you have them mapped to? I have `<Super>Left,<Super>h` for "Select window left", for instance. Similar vim keys for the other directions and it's currently working for me.

I'm guessing either the mapping is not input correctly, or it's conflicting with some other system setting?

**Comment by rustysec** [comment]
Also if you run `journalctl -xf /usr/bin/gnome-shell` while trying to use the shortcuts, you can see any errors that might be getting thrown in the background.

**Comment by REIS0** [comment]
Here's the output
```
-- Logs begin at Sat 2020-01-25 21:17:55 -03. --
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Feb 16 23:53:46 pop-os gnome-shell[6846]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Feb 16 23:53:47 pop-os gnome-shell[6846]: spiral.js: adding window 3225015042 to spiral 0, 0
Feb 16 23:53:48 pop-os gnome-shell[6846]: spiral.js: adding window 3225015043 to spiral 0, 0
Feb 16 23:54:00 pop-os gnome-shell[6846]: Usage of object.actor is deprecated for ButtonBox
                                          get@resource:///org/gnome/shell/ui/environment.js:249:29
                                          onTrayIconAdded/<@/home/arthur/.local/share/gnome-shell/extensions/tray-icons@zhangkaizhao.com/extension.js:68:9
Feb 16 23:54:34 pop-os gnome-shell[6846]: spiral.js: adding window 3225015045 to spiral 1, 0
Feb 16 23:54:46 pop-os org.gnome.tweaks.desktop[6846]: WARNING : Error loading desktopfile: /home/arthur/.config/autostart/redshift-gtk.desktop
Feb 16 23:54:47 pop-os gnome-shell[6846]: spiral.js: adding window 3225015046 to spiral 2, 0
Feb 16 23:54:51 pop-os gnome-shell[6846]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6400007
```

and here's my keybindings
![image](https://user-images.githubusercontent.com/38042161/74620474-30ab4700-5131-11ea-8d56-52db36071b23.png)

as I said for some reason rolling back to older commit makes it work, I'm gonna roll back and paste the output here

**Comment by rustysec** [comment]
What other extensions do you have installed? Dash to panel? Do you use multiple monitors?

**Comment by REIS0** [comment]
Besides the one that already come with Pop_OS!, I have: dash to dock, caffeine, workspace switcher, tray icons, notification remover.

**Comment by rustysec** [comment]
Ok, I'll try to reproduce with dash to dock and see where that gets me. Thanks for the info.

**Comment by rustysec** [comment]
I set my keybindings to yours and there is definitely something odd happening. The defaults work fine, but getting inconsistent results with `<Control><Alt>Arrow` might be something conflicting... and it doesn't seem to be related to dash to panel.

**Comment by rustysec** [comment]
Aha, I bet your gaps are set to 0, right?

**Comment by rustysec** [comment]
Thanks for the bug report, that was a silly oversight on my part.
