### ISSUE TITLE
How do I add multiple "Always Float" alternatives.

### ISSUE THREAD

**Issue by arvids** [rustysec/tidalwm#36]
Hi, 
According to #6, I should be able to add multiple options but it does not work with a comma seperated list. 
`
TidalWM, gnome-tweaks`
results in only the TidalWM preferences starting in floating and 

`gnome-tweaks, TidalWM`
is the opposite with the TidalWM preferences being tiled once more.

**Comment by rustysec** [comment]
Do not use any spaces after the comma, that should clear it up.

**Comment by arvids** [comment]
Oh right, thank you for the quick response!
