### ISSUE TITLE
Termite not tiling

### ISSUE THREAD

**Issue by py9mrg** [rustysec/tidalwm#38]
Hello,

First of all, thanks for this great extension. I've just installed and love it. Have a couple of bugs to report though so will do them separately. First is:

Termite is not working at all. When it opens it just floats above everything and no way to get it tiling.

**Comment by rustysec** [comment]
That's interesting, termite is my go to terminal. Did you log out and back in after you installed the extension?

**Comment by py9mrg** [comment]
Yeah I thought it was weird as well given you reference it in the read me. I did log out and in again. Although, thinking about it, I had done some updates without restarting. On my phone now so will have a go again tomorrow and let you know if it’s still happening.

**Comment by rustysec** [comment]
Definitely let me know, thanks for the report.

**Comment by rustysec** [comment]
Also are you on x11 or wayland?

**Comment by nodefourtytwo** [comment]
I have the same issue. Using Wayland. All other terminals (gnome-terminal, alacritty, kitty) tile fine.

It used to work fine. I updated to the latest version this morning, and it's not tiling anymore. I'll try to find the commit that introduced this behavior.

Also, thanks for this extension. I love it.

**Comment by nodefourtytwo** [comment]
That's the commit: https://github.com/rustysec/tidalwm/commit/96474fb8d9e64bdf0faffeb630ee2f85a80a9e09

**Comment by rustysec** [comment]
Awesome work, this is a little confusing. When I launch termite it is tiling in fine, and the window title is not empty. What distro is everyone on?

**Comment by nodefourtytwo** [comment]
Arch

**Comment by rustysec** [comment]
What shells are you using? bash?

**Comment by nodefourtytwo** [comment]
zsh

**Comment by nodefourtytwo** [comment]
The only option I see in termite conf that could matter is: dynamic_title = true

**Comment by rustysec** [comment]
I cannot figure out how to repro the problem but testing with the provided patch looks good.

**Comment by py9mrg** [comment]
Can confirm the patch fixes this for me.
