### ISSUE TITLE
Settings doesn't auto resize

### ISSUE THREAD

**Issue by py9mrg** [rustysec/tidalwm#39]
When trying to configure TidalWM, the settings window opens as part of the tiling but doesn't resize so it runs off the screen.

**Comment by rustysec** [comment]
Best to float the window: with it selected the default is `<ctrl><alt>f` then you can resize.

**Comment by rustysec** [comment]
@py9mrg does floating solve the issue?

**Comment by py9mrg** [comment]
Sorry for the delay - no floating doesn't seem to sort it. I can move the window but it won't resize.

**Comment by rustysec** [comment]
Ok, so the expected behavior here is that it is resized to fit on the screen and maybe centered?

**Comment by rustysec** [comment]
I implemented auto-center and resizing of floated windows. On my system this seems to fix the behavior you reported. Let me know if it's still not 100% what you think it should be.

**Comment by rustysec** [comment]
I'm going to close this assuming the changes have solved the original issue. Feel free to reopen if you feel otherwise.
