### ISSUE TITLE
Default "select window right" hotkey conflicts with gnome "Lock screen" hotkey

### ISSUE THREAD

**Issue by nodefourtytwo** [rustysec/tidalwm#40]
The extension defaults to "Super+L" to select the window on the right. Gnome defaults (I think) to "Super + L" to lock the screen. It took me a very long time to find out why I could not lock my session anymore.

**Comment by arvids** [comment]
The default for select window to the left is also in conflict with gnome defaults (Super+H). At least the readme should include something about gnome defaults conflicts.

**Comment by rustysec** [comment]
Do you think the best option is to disable the gnome defaults? Or pick different defaults? These are the bindings most likely used by people coming from i3 or sway.

**Comment by nodefourtytwo** [comment]
I think that, since it's a Gnome extension, it should respect Gnome defaults. 
You make a point though that i3 and sway users would want it that way. IMHO, if you decide to keep it as it is, @arvids proposition to add a warning in the readme is fine.

**Comment by rustysec** [comment]
I think `Super+Left` and `Super+Right` are also gnome defaults for window split, right?

**Comment by arvids** [comment]
Super+Up and Super+Down as well.

**Comment by rustysec** [comment]
The quickest solution is to document it in the readme, a "cooler" solution can come later.

**Comment by odysseyalive** [comment]
My apologies for waking a closed issue, but this appeared to be the only appropriate place to continue this conversation. 

 I use the standard Gnome hot keys all the time, some of which conflict with TidalWM defaults.  The following hot keys are a bit  more ergonomic.  They don't conflict with anything else, either.  In which case, these defaults seem to address the initial issue I had too:

`
Float Window: <Ctrl><Super>f
`
`
Rotate Windows: <Ctrl><Super>r
`
`
Increase Horizontal Split: <Ctrl><Super>Right
`
`
Decreased Horizontal Split: <Ctrl><Super>Left
`
`
Increase Vertical Split: <Ctrl><Super>Up
`
`
Decrease Vertical Split: <Ctrl><Super>Down
`
`
Select Window Above: <Ctrl><Super>k
`
`
Select Window Below: <Ctrl><Super>j
`
`
Select Window Left: <Ctrl><Super>h
`
`
Select Window Right: <Ctrl><Super>l
`
