### ISSUE TITLE
After opening an app and changing the workspace it becomes huge and takes more than one monitor space

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#45]
As you can see below is quite bizarre thing

![bug](https://user-images.githubusercontent.com/38042161/78128831-18079f80-7406-11ea-9844-4e3f3dea549e.png)

As you can see the space that Slack is occupying is too much, it scale way more than screen and goes to the workspace in my other monitor, even staying above telegram

Steps to reproduce (I need to check it better):
1. Click to open an app
2. While is loading change the workspace really fast
3. Apparently after this the bug happens

I've got this bug quite sometimes, I'm not really sure is it happens only with flatpaks since only experienced with them, If I  figure out something more I'll update here.

**Comment by rustysec** [comment]
I can reproduce this with non-flatpak apps if I switch workspaces right after opening. Very strange, i'll see what i can figure out. thanks for the report!

**Comment by rustysec** [comment]
I added some safeguards around this and haven't been able to reproduce on my end. If you pull master and try to trigger this behavior, that'd be very helpful. Hopefully it's fixed :crossed_fingers:

**Comment by REIS0** [comment]
I'll try it for some days and update here

**Comment by REIS0** [comment]
So far no I could not reproduce the bug anymore, I'm closing this one.

**Comment by REIS0** [comment]
Apparently I got to reproduce the bug again, happened to me only very few times but still got it

As you can see it happened with both gimp and thunderbird, but even then I've got some difficult trying to reproduce it again compared to last time

![Untitled](https://user-images.githubusercontent.com/38042161/79609579-875bdf80-80e6-11ea-8747-3a60b994da65.png)
![Screenshot from 2020-04-15 17-34-47](https://user-images.githubusercontent.com/38042161/79609597-8cb92a00-80e6-11ea-8a51-7af5619586a6.png)

**Comment by rustysec** [comment]
I cannot get this to happen on my system, even rapid fire workspace switching while gimp is loading. What version of gnome are you running?

**Comment by REIS0** [comment]
3.34.3

**Comment by REIS0** [comment]
It's been a while since I don't get any error like this any more I'm closing this one
