### ISSUE TITLE
Initial split direction doesn't work

### ISSUE THREAD

**Issue by Spryc** [rustysec/tidalwm#46]
So when i try to put initial split direction to vertical it doesn't do anything. and when i go in to settings afterwards it's set to horizontal again

**Comment by rustysec** [comment]
Wow, don't know how this was missed. I'll take a look at it later, should be an easy fix.

**Comment by rustysec** [comment]
I tested fixes and it's now working for me. Pull master and give it a try when you have a chance.

**Comment by rustysec** [comment]
@Spryc i'm going to close this, feel free to reopen if it's still giving you problems.
