### ISSUE TITLE
[Bug] Tidal auto installed after update and is broken?

### ISSUE THREAD

**Issue by DanMeadWasTaken** [rustysec/tidalwm#57]
So, i love using tidal, and was sad to find that when i tried installing it on my new laptop, it was non-existent in the gnome extension website. Yet for some reason when i updated, it auto-installed itself. So, i went to turn it on, but cannot do anything with the settings. I get this error code (no worries on the account name, it's a fake name anyway):

The settings of extension tidalwm@rustysec.github.io had an error:
```
Error: No property margin on GtkGrid
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
buildPrefsWidget@/home/danmead/.local/share/gnome-shell/extensions/tidalwm@rustysec.github.io/prefs.js:25:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by DanMeadWasTaken** [comment]
If this could be fixed, i'd be super grateful. I love using a combo of float and tilling, but most others I've found don't allow me the fine tuned control to individually move things around with key-binds. Which i only really need when i'm working on something, otherwise i'm using float.

**Comment by odysseyalive** [comment]
Yeah.  The only similar option is the Material-Shell in zen-mode.  

However, I much prefer the way TidalWM works.  Gnome 40+ has some major changes and hurdles though.

**Comment by rustysec** [comment]
Thanks for the report, I really need to get in and fix all these gnome compat issues. There was a lot of changes in every version of gnome, and I just have not had time to devote to fixing them all.
