### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#7]
I've tried to install in both notebook and virtual machine but it doesn't seem to work, I'm using Pop_OS! 19.10 in both.

![Screenshot from 2020-01-21 17-13-52](https://user-images.githubusercontent.com/38042161/72839904-eccc3b80-3c71-11ea-9e9d-92b195a3a173.png)

**Comment by rustysec** [comment]
I need to update the readme to include "log out and log back in". Have you attempted that?

**Comment by REIS0** [comment]
At least in the vm just rebooting worked, gonna try later in my notebook but it was probably it.
