### ISSUE TITLE
Gaps when is set to no gaps

### ISSUE THREAD

**Issue by REIS0** [rustysec/tidalwm#8]
When I try to set the gaps between windows to 0 it starts to become a little buggy, sometimes the tilling simply stops. The first behaviour happened in both notebook and virtual machine.

Steps to reproduce:

- Just set Window Gaps to 0

![Screenshot from 2020-01-21 17-44-15](https://user-images.githubusercontent.com/38042161/72842808-ee98fd80-3c77-11ea-8eb4-877e8f59e2b8.png)

![Screenshot from 2020-01-21 17-44-23](https://user-images.githubusercontent.com/38042161/72842826-fa84bf80-3c77-11ea-8c09-7cd2c3b5e145.png)

![Screenshot from 2020-01-21 17-59-33](https://user-images.githubusercontent.com/38042161/72842834-ffe20a00-3c77-11ea-971e-b3ac827de4bb.png)

OBS: I'm currently using the hybrid graphic mode which uses both integrated Intel and Nvidia gpu.

**Comment by rustysec** [comment]
Interesting, I hadn't seen this issue. Just for fun if you try un-tiling them and re-tiling? I can have a look at it later today.

**Comment by REIS0** [comment]
Nothing changes, also tried to disable and enable again the extension, at first I've though it was something related to Nvidia drivers but since this also happened in the vm I can't say they have relation.
Maybe something related to Pop_OS! itself?

**Comment by rustysec** [comment]
Is pop gnome 3.34? I need to spin it up in a VM to test on pop, I only use vanilla gnome regularly.

**Comment by REIS0** [comment]
Yes it is

**Comment by rustysec** [comment]
Ok thanks, well unfortunately I don't have an answer for you at the moment, but I'll definitely look at it tonight. 

Do you have issues when gaps are > 0?

**Comment by REIS0** [comment]
Didn't noticed any, so far I've only tested the default config and the one without gaps, in the default didn't have any problems at all.

**Comment by rustysec** [comment]
Awesome, I'll get it patched up tonight and if you could help confirm the fix I'd be grateful.

**Comment by REIS0** [comment]
well got to reproduce it in fedora inside a virtual machine, but looks like it only afected the gnome terminal
![image](https://user-images.githubusercontent.com/38042161/72854491-73057380-3cac-11ea-934f-abfb6a9405d0.png)

As soon I receive the notification for the patch I'll try it

**Comment by rustysec** [comment]
i knew i had encountered this report somewhere before, just had to find it. there are a number of issues with gnome-terminal regarding tiling:

[gtile #86](https://github.com/gTile/gTile/issues/86)
[gtile #88](https://github.com/gTile/gTile/issues/88)

i feel like i'm being bitten by the same wackiness. may take me a little longer than anticipated to figure it out.

**Comment by REIS0** [comment]
Gonna use my alacritty configs, looks like a problem with terminals that use gtk, I'll test it again in fedora with alacritty

**Comment by rustysec** [comment]
hrm, seems like gnome-terminal is the culprit. tilix and terminator are working as expected for me.

[also found this shelltile bug](https://github.com/emasab/shelltile/issues/64)

**Comment by REIS0** [comment]
looks like was it, testing here on notebook after changing to alacritty and no issues so far.

**Comment by REIS0** [comment]
Maybe more like something that could benefit is when there's only one app in the workspace the same app goes to full mode, just like clicking twice or pressing Super+Ctrl+Up, I don't know how difficult it is to do this so maybe looking into it later.
So far the issue has been resolved, gtk terminals don't like tilling.
